apiVersion: apps/v1
kind: Deployment
metadata:
  name: bayviewimage2
  labels:
    app: bayviewimage2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bayviewimage2
  template:
    metadata:
      labels:
        app: bayviewimage2
    spec:
      containers:
      - name: bayviewimage2
        image: joyceyprojectregistry.azurecr.io/image
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bayviewimage2
spec:
  selector:
    app: bayviewimage2
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bayviewimage2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: <your-domain>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bayviewimage2
            port:
              number: 80
